spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Mavenpro
spring.datasource.username=Dhiraj
spring.datasource.password=Dhiraj@8317

spring.datasource.driver-class-name=org.postgresql.Driver